# Generated by Django 6.0.3 on 2026-03-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('solution_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('passkey', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('problems', models.ManyToManyField(blank=True, related_name='contests', to='home.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text="Input given to the student's program")),
                ('expected_output', models.TextField(help_text='What the program should return')),
                ('is_sample', models.BooleanField(default=False, help_text='Visible to students for debugging')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for sample cases', null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='home.problem')),
            ],
        ),
    ]
