# Generated by Django 6.0.3 on 2026-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contest_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='home.ContestProblem', to='home.problem'),
        ),
    ]
