# Generated by Django 6.0.3 on 2026-03-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problem_contest_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='points',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution_code',
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
            ],
            options={
                'unique_together': {('contest', 'problem')},
            },
        ),
    ]
