# Generated by Django 6.0.3 on 2026-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contest_is_active_remove_contest_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='home.ContestProblem', to='home.problem'),
        ),
    ]
