# Generated by Django 3.1.1 on 2026-04-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contest_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='prize',
            field=models.CharField(blank=True, help_text='Prize pool info', max_length=100),
        ),
        migrations.AddField(
            model_name='contest',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. AI, WEB, DSA)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
