# Generated by Django 4.2.30 on 2026-04-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20260424_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('ace_mode', models.CharField(help_text='Used for IDE syntax highlighting', max_length=50)),
                ('extension', models.CharField(default='.py', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='is_special_judge',
            field=models.BooleanField(default=False, help_text='Check output via custom logic rather than exact match'),
        ),
        migrations.AddField(
            model_name='problem',
            name='special_judge_script',
            field=models.TextField(blank=True, help_text='Python script to validate output', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='passkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error')], default='PENDING', max_length=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Seconds')),
                ('memory_used', models.IntegerField(default=0, help_text='KB')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='home.contest')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MANDATORY', 'Must Use'), ('FORBIDDEN', 'Must Not Use'), ('STRUCTURAL', 'Structural Check (e.g. Recursion)')], max_length=20)),
                ('keyword', models.CharField(help_text="The function/method name (e.g. 'math.sqrt' or 'for')", max_length=100)),
                ('error_message', models.CharField(help_text='User-friendly error if rule is broken', max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='home.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='allowed_languages',
            field=models.ManyToManyField(related_name='problems', to='home.language'),
        ),
        migrations.CreateModel(
            name='UserProblemSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest', 'problem')},
            },
        ),
    ]
