# Generated by Django 4.2.30 on 2026-04-30 20:35

from django.db import migrations, models


def populate_difficulty_from_points(apps, schema_editor):
    ContestProblem = apps.get_model('home', 'ContestProblem')
    ContestProblem.objects.filter(points__lte=10).update(difficulty='EASY')
    ContestProblem.objects.filter(points__gt=10, points__lte=30).update(difficulty='MEDIUM')
    ContestProblem.objects.filter(points__gt=30).update(difficulty='HARD')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_language_problem_is_special_judge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.RunPython(populate_difficulty_from_points, migrations.RunPython.noop),
    ]
