# Generated by Django 4.2.30 on 2026-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contestproblem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_stubs',
            field=models.TextField(blank=True, help_text='JSON mapping (as text) of language slug or ace_mode to code stub. Example: {"python3": "def solve():\\n    pass", "cpp": "int main() {}"}', null=True),
        ),
    ]
