# Generated by Django 4.2.30 on 2026-04-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_problem_code_stubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCodeStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Code stub for the selected language')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codestubs', to='home.problem')),
            ],
            options={
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
