# Generated by Django 3.1.1 on 2026-04-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20260501_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code_stubs',
        ),
    ]
