# Generated by Django 3.1.1 on 2026-04-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_problem_code_stubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_code', models.TextField(blank=True, default='', help_text='Starter template boilerplate')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stubs', to='home.problem')),
            ],
            options={
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
