# Generated by Django 3.1.1 on 2026-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_codestub'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='compile_command',
            field=models.CharField(blank=True, help_text='Optional. Use {filename} for source file.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='docker_image',
            field=models.CharField(default='python:3.12-slim', help_text='Docker image to use (e.g. gcc:latest)', max_length=100),
        ),
        migrations.AddField(
            model_name='language',
            name='run_command',
            field=models.CharField(default='python {filename}', help_text='Command to run. Use {filename} for source file.', max_length=255),
        ),
    ]
