# Generated by Django 3.1.1 on 2026-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_codestub'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, help_text='Compilation or Runtime errors', null=True),
        ),
    ]
