# Generated by Django 3.1.1 on 2026-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_submission_error_message'),
        ('home', '0014_auto_20260511_0043'),
    ]

    operations = [
    ]
