# Generated by Django 3.1.1 on 2026-05-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20260512_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemrule',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all languages', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.language'),
        ),
        migrations.AlterField(
            model_name='problemrule',
            name='keyword',
            field=models.CharField(help_text="Exact token (e.g. 'set') OR Structure (e.g. 'recursion', 'inheritance', 'lines_5')", max_length=100),
        ),
        migrations.AlterField(
            model_name='problemrule',
            name='rule_type',
            field=models.CharField(choices=[('MANDATORY', 'Must Use (Exact Token)'), ('FORBIDDEN', 'Must Not Use (Exact Token)'), ('STRUCTURAL', 'Structural Check (e.g. recursion, inheritance, lines_X)')], max_length=20),
        ),
    ]
