# Generated by Django 3.1.1 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20260517_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='penalty_minutes',
            field=models.IntegerField(default=10, help_text='Penalty in minutes added per wrong submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_awarded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_time_taken',
            field=models.FloatField(default=0.0, help_text='Total time to solve in minutes, including penalties'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AC', 'Accepted'), ('PARTIAL', 'Partial'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error')], default='PENDING', max_length=10),
        ),
    ]
