# Generated by Django 6.0.5 on 2026-05-21 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contest_is_team_contest_alter_codestub_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='input_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_format',
            field=models.CharField(choices=[('EDITOR', 'Standard Text Stream'), ('UPLOAD', 'Physical File')], default='EDITOR', max_length=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_format',
            field=models.CharField(choices=[('EDITOR', 'Standard Text Stream'), ('UPLOAD', 'Physical File')], default='EDITOR', max_length=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
