# Generated by Django 6.0.5 on 2026-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_testcase_input_filename_testcase_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='testcase_inputs/'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='testcase_outputs/'),
        ),
    ]
