# Generated by Django 6.0.5 on 2026-05-31 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_testcase_expected_output_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_anti_cheat',
            field=models.BooleanField(default=True, help_text='Master toggle for the anti-cheat proctoring framework.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch / Blur'), ('CLIPBOARD', 'Clipboard Access'), ('DEVTOOLS', 'DevTools Opened'), ('FULLSCREEN', 'Fullscreen Exited'), ('DOM_INJECTION', 'DOM Injection Detect')], max_length=20)),
                ('strike_number', models.IntegerField(help_text='Strike sequence number (e.g. 1, 2, 3)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Contextual details of the violation', null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='home.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disqualified', models.BooleanField(default=False, help_text='Designates whether the user is disqualified from this contest.')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='home.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
